
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  host: "http://localhost:3000"
  secret_key_base: 66a872ec6c3c9792822a05540960481ee81d6d039e8bf63053ca3b33ed9e94c991ba27ac856e583ccb3e3c6ae1422c51fe557441a4a220f672f605a775575daes

test:
  secret_key_base: a732051c56c5efa00ee16c65d73e2d199be8127b0af7131b6fcbceda13d99224e34e631d1e6d9f39125ced4bf19ae23699c923f88307e3e5ef758a6d100bb70e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: f54e1ed4c5ac6c4047c72ddb0dc1c86f2a1d1fc5c646ca93890e0f31573a0fe7e62e5e846fd1dbce1163c483d8b50d67e10f4919fa20d1a5eaba6ca5dd8d6d1e
  host: "http://localhost:3000"

